version: '3.7'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
 
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"  # InfluxDB API
    environment:
      - INFLUXDB_DB=k6
       - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      # - INFLUXDB_ADMIN_ORG=Performance
      # - INFLUXDB_ADMIN_BUCKET=Performance
      #  - INFLUXDB_ADMIN_TOKEN=Bag_TO_WBSGypEDhxA07tkEnKX5GYd5c8DPOk-S4zCn1BgCw2IqZULM2OpY7NZPcVbzvAFxSsueSuNmkpyJrsw==
    volumes:
      - influxdb-data:/var/lib/influxdb
 
  k6:
    image: grafana/k6
    container_name: k6
    entrypoint: >
     k6 run  --out influxdb=http://influxdb:8086/k6 /scripts/k6script.js
 
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/scripts  # Mount local scripts directory to /scripts in container
 
volumes:
  grafana-data:
  influxdb-data:
